apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patches:
- path: env.yaml
- path: ingress.yaml
namespace: prod
images:
  - name: demo
    newName: harbor.local.com/devops/spring_boot_demo
    newTag: master-c9cd9569